trigger:
  - main

variables:
  - group: azure-credentials

stages:
  - stage: Build
    jobs:
      - job: BuildAndPush
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Azure Container Registry'
              repository: 'backend'
              command: 'buildAndPush'
              Dockerfile: 'backend/Dockerfile'
              
          - task: Docker@2
            inputs:
              containerRegistry: 'Azure Container Registry'
              repository: 'frontend'
              command: 'buildAndPush'
              Dockerfile: 'frontend/Dockerfile'

  - stage: Deploy
    jobs:
      - job: DeployToAzure
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appName: '$(APP_NAME)'
              containers: |
                $(ACR_NAME).azurecr.io/backend:$(Build.BuildId)
                $(ACR_NAME).azurecr.io/frontend:$(Build.BuildId)
